services:
    webdevText.twig.extension:
        class: Webdev\BlogBundle\Extension\TextExtension
        tags:
            - { name: twig.extension }
            
    webdev.blog.admin.post:
      class: Webdev\BlogBundle\Admin\PostAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: webdevblog, label: Posts }
      arguments: [null, Webdev\BlogBundle\Entity\Post, SonataAdminBundle:CRUD]
