parameters:
    database_driver: pdo_mysql
    database_host: backender.ch
    database_port: '3306'
    database_name: c1001
    database_user: c1001
    database_password: 'mjdiablo'
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c71be263db8a7539cccd60453d41b3ea63f54fd4
