parameters:
    database_driver:   pdo_mysql
    database_host:     codag.net
    database_port:     ~
    database_name:     c1002
    database_user:     c1002
    database_password: mjdiablo

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
