<?php

namespace Webdev\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogrollRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogrollRepository extends EntityRepository
{
}