services:        
    backender.blog.admin.post:
      class: Backender\BlogBundle\Admin\PostAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Article Handling, label: Posts }
      arguments: [null, Backender\BlogBundle\Entity\Post, SonataAdminBundle:CRUD, @service_container]
      
    backender.blog.admin.comment:
      class: Backender\BlogBundle\Admin\CommentAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Article Handling, label: Comments }
      arguments: [null, Backender\BlogBundle\Entity\Comment, SonataAdminBundle:CRUD]

    backender.blog.admin.tag:
      class: Backender\BlogBundle\Admin\TagAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Article Handling, label: Tags }
      arguments: [null, Backender\BlogBundle\Entity\Tag, SonataAdminBundle:CRUD]

    backender.blog.admin.blogroll:
      class: Backender\BlogBundle\Admin\BlogrollAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Article Handling, label: Blogroll }
      arguments: [null, Backender\BlogBundle\Entity\Blogroll, SonataAdminBundle:CRUD]

    backender.blog.post:
        class: Backender\BlogBundle\Extension\PostService
        #arguments: ['@service_container']

    backender.blog.blogroll.controller:
        class: Backender\BlogBundle\Controller\BlogrollController

    backender.blog.post.listener:
      class: Backender\BlogBundle\Listener\PostListener
      arguments: ['@service_container']
      tags: 
        - { name: doctrine.event_listener, event: prePersist }
    
    #SYSMFONY CORE CLASSES (override)
    #form.type.form:
    #  class: Backender\BlogBundle\Form\Extension\Core\Type\BackenderFormType
    #  tags:
    #    - { name: form.type, alias: form }

        